### ISSUE TITLE
How user with Class View ?

### ISSUE THREAD

**Issue by flaudizio** [prymitive/bootstrap-breadcrumbs#26]
How can I use with url MyListView.as_view() ?

Like:

    {% breadcrumb "My View" "MyviewListView.as_view()" %}

My url:
    url(r'^myview/view/(?P<pk>[0-9]+)/$', MyViewDetail.as_view(), name='myview_detail'),

Thank's a lot.

**Comment by prymitive** [comment]
you can pass the name as argument:

```
{% breadcrumb "My View" "myview_detail" %}
```

**Comment by flaudizio** [comment]
Thank's.
