### ISSUE TITLE
the templates aren't support to rich snippets

### ISSUE THREAD

**Issue by pycarlos** [prymitive/bootstrap-breadcrumbs#30]
the templates aren't support to rich snippets
in the next link you can see the implementation examples and info:
https://developers.google.com/search/docs/data-types/breadcrumbs

**Comment by prymitive** [comment]
I'm not sure what do you request here. Templates provided with the package are basic templates for bootstrap and they are based on bootstrap docs. The goal of those template is to support most common cases, if you have special needs use a custom template and point `BREADCRUMBS_TEMPLATE` to it.

**Comment by pycarlos** [comment]
The rich snippets are important for SEO, and I think that bootstrap-breadcrumbs should be SEO friendly.

**Comment by prymitive** [comment]
If it's important to you then feel free to raise a pull request. Thanks
