### ISSUE TITLE
No module named 'django.core.urlresolvers'

### ISSUE THREAD

**Issue by djpremier** [prymitive/bootstrap-breadcrumbs#41]
As of version 2.0 of Django is no longer an application to module 'django.core.urlresolvers'. Follow the message:

> Deprecated since version 1.10:
> In older versions, these functions are located in django.core.urlresolvers. Importing from the old location will continue to work until Django 2.0

For a generic solution, you can do the following:

```
# ... imports

if VERSION < (2, 0):
    from django.core.urlresolvers import (reverse, resolve, NoReverseMatch,
                                          Resolver404)
else:
    from django.urls import (reverse, resolve, NoReverseMatch,
                             Resolver404)

# ... Remainder of code
```

**Comment by prymitive** [comment]
Thanks, #42 should fix this

**Comment by prymitive** [comment]
Please try [v0.9.0rc1](https://github.com/prymitive/bootstrap-breadcrumbs/releases/tag/v0.9.0rc1)
