### ISSUE TITLE
Space between slash and crumb

### ISSUE THREAD

**Issue by davidmoremad** [prymitive/bootstrap-breadcrumbs#56]
Version: `django-bootstrap-breadcrumbs==0.9.1`

The breadcrumbs should looks like `Home / Users / John Doe` but it looks like `Home /Users /John Doe`. (See the lack of space between the slash and the word)

base.py
```
  {% block breadcrumbs %}
    {% breadcrumb "Home" "/" %}
  {% endblock %}
```

users.py
```
{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Users" "users" %}
{% endblock %}
```

profile.py
```
{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb id "users.views.profile" user.username %}
{% endblock %}
```

---
The fix I'm using:

```
ul.breadcrumb span.divider{
  margin-right: 5px;
}
```

**Comment by prymitive** [comment]
Which template are you using and what's your bootstrap version?

**Comment by davidmoremad** [comment]
Im using `bootstrap 4.1.3` and `breadcrumb` & `breadcrumb_safe` templates.

**Comment by prymitive** [comment]
By "template" I mean the HTML template, default one is for bootstrap v2, see [docs section](https://django-bootstrap-breadcrumbs.readthedocs.io/en/latest/#rendering-breadcrumbs) on that.
You probably want to add `BREADCRUMBS_TEMPLATE = "django_bootstrap_breadcrumbs/bootstrap4.html"` to `settings.py`

**Comment by davidmoremad** [comment]
That solves my problem. Was the breadcrumbs_template.

Cheers !
